php_packages:
  - php7.3
  - php7.3-common
  - php7.3-cli
  - php7.3-fpm
  - php7.3-mysql
  - php7.3-zip
  - php7.3-xml
  - php7.3-mbstring

php_timezone: Europe/Paris
php_upload_max_filesize: "20M"
php_post_max_size: "20M"
php_memory_limit: "256M"
